"""Typed service interfaces exposed to HTTP routes."""

from __future__ import annotations

from collections.abc import Sequence
from dataclasses import dataclass
from typing import IO, Any, Protocol

from ..models import ActionResult, DiagnosticResult, PlaybackSummary


class SourceChoice(Protocol):
    @property
    def name(self) -> str: ...

    @property
    def address(self) -> str: ...

    @property
    def selection_value(self) -> str: ...

    @property
    def display_label(self) -> str: ...


class AuthenticationService(Protocol):
    @property
    def secret_key(self) -> str | bytes: ...

    @property
    def password_digest(self) -> str:
        """Bind a browser session to the password it was issued against."""
        ...

    def authenticate(self, password: str, previous_session_id: str | None) -> str | None: ...
    def is_current(self) -> bool: ...
    def revoke(self, session_id: str | None) -> None: ...


class SourcePlaybackService(Protocol):
    def sources(self) -> Sequence[SourceChoice]: ...
    def configuration(self) -> tuple[str, str]: ...
    def playback(self) -> PlaybackSummary: ...
    def select(self, selection: str) -> ActionResult: ...
    def refresh(self) -> None: ...
    def restart(self) -> ActionResult: ...
    def clear(self) -> ActionResult: ...
    def save_direct(self, address: str) -> ActionResult: ...


class NetworkService(Protocol):
    def read(self) -> dict[str, Any]: ...
    def save(self, discovery_server: str) -> ActionResult: ...


class DiagnosticsService(Protocol):
    def version(self) -> str: ...
    def status(self) -> str: ...
    def discovery(self) -> DiagnosticResult: ...
    def runtime(self) -> DiagnosticResult: ...
    def direct(self, address: str) -> DiagnosticResult: ...
    def bundle(self, include_packet_capture: bool = False) -> tuple[IO[bytes], str]: ...


class SystemService(Protocol):
    def request_reboot(self) -> ActionResult: ...


@dataclass(frozen=True)
class ServiceContainer:
    auth: AuthenticationService
    source: SourcePlaybackService
    network: NetworkService
    diagnostics: DiagnosticsService
    system: SystemService
