// Copyright (c) 2026 Matthew David Miller
// SPDX-License-Identifier: MIT
//! Compiles the manifest-v3 capsule into the deployer.
//!
//! Everything the Raspberry Pi receives -- the host scripts, the `OpenRC`
//! services, the compose file, the legal texts, and the ARM64 image archive --
//! is embedded here, so the operator's copy of the deployer is the whole
//! appliance and needs no checkout beside it.
//!
//! `deploy/manifest-v3.txt` remains the single definition of that set: this
//! reads it and emits one `include_bytes!` per member. A member added there is
//! embedded without a second list to keep in step, and a member named there but
//! missing from disk fails this build rather than a deployment.

use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};
use std::process;

/// Cargo's own limit on what it will accept back from a build script line.
const MAX_MEMBERS: usize = 128;

fn fail(message: &str) -> ! {
    eprintln!("error: {message}");
    process::exit(1);
}

fn variable(name: &str) -> String {
    match std::env::var(name) {
        Ok(value) => value,
        Err(error) => fail(&format!("{name} is unreadable: {error}")),
    }
}

/// The same rule as `valid_manifest_name` in `lib.rs`.
///
/// Duplicated because a build script cannot depend on the crate it builds.
/// `capsule::tests::embedded_names_are_safe_manifest_members` runs the real
/// rule over what this accepted, so the two cannot drift apart silently.
fn safe_member(value: &str) -> bool {
    !value.is_empty()
        && value.len() <= 240
        && !value.starts_with('/')
        && !value.ends_with('/')
        && !value.contains("//")
        && value.is_ascii()
        && value
            .bytes()
            .all(|b| b.is_ascii_alphanumeric() || b"._-/".contains(&b))
        && value
            .split('/')
            .all(|part| !matches!(part, "" | "." | ".."))
}

/// The remedy for the one member no checkout contains until it is built.
fn missing_member(root: &Path, name: &str) -> ! {
    if name.ends_with(".tar.gz") {
        fail(&format!(
            "{name} is not in {}.\n\
             The deployer embeds the appliance image, so the image has to exist before \
             the deployer can be built:\n    make build-arm64",
            root.display()
        ));
    }
    fail(&format!(
        "deploy/manifest-v3.txt names {name}, which is not in {}",
        root.display()
    ));
}

fn main() {
    let crate_dir = PathBuf::from(variable("CARGO_MANIFEST_DIR"));
    let Some(root) = crate_dir
        .parent()
        .and_then(Path::parent)
        .map(Path::to_path_buf)
    else {
        fail("the workspace root is not two levels above this crate");
    };
    let manifest = root.join("deploy/manifest-v3.txt");
    println!("cargo::rerun-if-changed={}", manifest.display());

    let text = match fs::read_to_string(&manifest) {
        Ok(text) => text,
        Err(error) => fail(&format!("{} is unreadable: {error}", manifest.display())),
    };
    let mut lines = text.lines();
    if lines.next() != Some("version=3") {
        fail(&format!(
            "{} is not a version=3 manifest",
            manifest.display()
        ));
    }

    let mut names: Vec<&str> = Vec::new();
    for line in lines {
        if !safe_member(line) {
            fail(&format!("unsafe manifest member: {line}"));
        }
        if names.contains(&line) {
            fail(&format!("duplicate manifest member: {line}"));
        }
        if names.len() == MAX_MEMBERS {
            fail("the manifest names more than 128 members");
        }
        let path = root.join(line);
        if !path.is_file() {
            missing_member(&root, line);
        }
        println!("cargo::rerun-if-changed={}", path.display());
        names.push(line);
    }
    if !names.contains(&"deploy/transaction.sh") || !names.contains(&"deploy/manifest-v3.txt") {
        fail("the manifest is missing its own transaction members");
    }

    let mut generated = String::from(
        "// @generated by build.rs from deploy/manifest-v3.txt. Do not edit.\n\
         pub(crate) static MEMBERS: &[CapsuleMember] = &[\n",
    );
    for name in &names {
        // Every name passed `safe_member`, so it holds no quote, backslash, or
        // non-ASCII byte that a Rust string literal would have to escape.
        let _ = writeln!(
            generated,
            "    CapsuleMember {{ name: \"{name}\", \
             bytes: include_bytes!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/../../{name}\")) }},"
        );
    }
    generated.push_str("];\n");

    let out = PathBuf::from(variable("OUT_DIR")).join("capsule.rs");
    if let Err(error) = fs::write(&out, generated) {
        fail(&format!("{} is unwritable: {error}", out.display()));
    }
}
