[package]
name = "omt-web"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
axum.workspace = true
axum-server.workspace = true
getrandom.workspace = true
hmac.workspace = true
libc.workspace = true
minijinja.workspace = true
nix.workspace = true
omt-protocol = { version = "0.9.54", path = "../omt-protocol" }
pbkdf2.workspace = true
quick-xml.workspace = true
rustls.workspace = true
scrypt.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_urlencoded.workspace = true
sha2.workspace = true
subtle.workspace = true
time.workspace = true
tokio = { workspace = true, features = ["process", "signal", "fs"] }
unicode-normalization.workspace = true
zip.workspace = true

[dev-dependencies]
tower = { version = "0.5.2", features = ["util"] }

[lints]
workspace = true
