<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>RpiOmt.Receiver.Core</RootNamespace>
    <AssemblyName>RpiOmt.Receiver.Core</AssemblyName>
    <IsAotCompatible>true</IsAotCompatible>
    <EnableNETAnalyzers>true</EnableNETAnalyzers>
  </PropertyGroup>
</Project>
