[package]
name = "omt-receiver"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
alsa.workspace = true
async-io.workspace = true
drm.workspace = true
futures-lite.workspace = true
omt-protocol = { version = "0.9.38", path = "../omt-protocol" }
omt-receiver-core = { version = "0.9.38", path = "../omt-receiver-core" }
quick-xml.workspace = true
serde.workspace = true
serde_json.workspace = true
signal-hook.workspace = true
vmx-decoder = { version = "0.9.38", path = "../vmx-decoder" }
zbus.workspace = true

[lints]
workspace = true

[[bin]]
name = "omt-receiver"
path = "src/main.rs"
