[package]
name = "rpi-omt-deployer"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[features]
default = []
desktop = ["dep:eframe", "dep:egui", "dep:rfd"]

[dependencies]
eframe = { workspace = true, optional = true }
egui = { workspace = true, optional = true }
rfd = { workspace = true, optional = true }
omt-deployer-core = { version = "0.9.55", path = "../omt-deployer-core" }
zeroize.workspace = true

[lints]
workspace = true

[[bin]]
name = "rpi-omt-deployer"
path = "src/main.rs"
