ARG PI_OS_VM_TOOLING_BASE
FROM ${PI_OS_VM_TOOLING_BASE}

RUN dnf install -y --setopt=install_weak_deps=False \
        coreutils \
        curl \
        findutils \
        grep \
        guestfs-tools \
        kernel-core \
        libguestfs \
        make \
        openssh-clients \
        procps-ng \
        qemu-system-aarch64-core \
        sed \
        tar \
        util-linux \
        xz \
    && dnf clean all

ENV LIBGUESTFS_BACKEND=direct
WORKDIR /workspace
USER 1000:1000
CMD ["/usr/bin/sleep", "infinity"]
