/* Copyright (c) 2026 Matthew David Miller
 * SPDX-License-Identifier: MIT
 *
 * The compiled page templates (templates_gen.c, generated by
 * tools/gen/gen_templates.py from src/web/templates).
 */
#ifndef OMT_WEB_TEMPLATES_H
#define OMT_WEB_TEMPLATES_H

#include "web/tv.h"

/* Renders the named page (e.g. "dashboard.html") into `out`. False for an
 * unknown page or a failed buffer. */
bool omt_template_render(const char *name, const tv *context, omt_buf *out);

/* The embedded static files ("style.css", "favicon.svg") and their types. */
bool omt_static_asset(const char *name, const char **data, size_t *len, const char **type);

#endif
